### PR TITLE
Add pull request template to the repo

### PR DESCRIPTION
**Pull request by wordshaker**
# Description of the Change

Add a pull request template

## Value

Standardise the information provided in pull requests and encourage pull request descriptions to be populated.

## Applicable Issues

N/A

### CODE REVIEW

**Comment by alefranz** [comment]
you are on 🔥!
As we have the `.github` folder, should we put in in there to keep the (already too crowded) root clean?

**Comment by wordshaker** [comment]
> you are on 🔥! As we have the `.github` folder, should we put in in there to keep the (already too crowded) root clean?

Yeah sure I'll shift it now

**Comment by wordshaker** [comment]
@alefranz I moved `codeowners` and `contributing.md` while I was there

**Review by alefranz — APPROVED** [review]
Nice! thank you!

**Pull request merged**
