### PR TITLE
Introduce API Name Convention

### PR DESCRIPTION
**Pull request by davidwhitney**
Migrating pull request from Pete Dawson.
---

This PR adds a convention around API names - relocating for conversation.

### CODE REVIEW

**Comment by davidwhitney** [comment]
```
Hi all,

With this pull request, I am proposing a ‘Title Convention’ to be added to the Architectural standards.

https://github.com/PeteDawson123/API-Design/pull/1

The value of this change is to ensure we have user-friendly titles going forward on the portal (so people can tell what things are!), examples of the problem below:
    

Please review my pull request and let me know if you need any changes made

Thanks,
Pete Dawson
Product Analyst - Developer Portal
London
[linkedin.com/in/pete-d-1ab49b150/](https://www.linkedin.com/in/pete-d-1ab49b150/)
```
@PeteDawson123

**Comment by davidwhitney** [comment]
Hi @PeteDawson123 

This seems rational - though I'd probably go further and suggest we shouldn't use "API" in those names at all as it's entirely implicit.

@alefranz @wordshaker thoughts?

**Comment by PeteDawson123** [comment]
> Hi @PeteDawson123
> 
> This seems rational - though I'd probably go further and suggest we shouldn't use "API" in those names at all as it's entirely implicit.
> 
> @alefranz @wordshaker thoughts?

I agree that API is implicit in there - our competitors seem to do both with and without. I chose to include it in ours as there are far more APIs with 'API' in their titles than not, this makes the problem far quicker to fix. Having said that, I'm happy to go with either based on your knowledge. Thank you

**Comment by PeteDawson123** [comment]
> Hi @PeteDawson123
> 
> This seems rational - though I'd probably go further and suggest we shouldn't use "API" in those names at all as it's entirely implicit.
> 
> @alefranz @wordshaker thoughts?

On reflection - it makes much more sense without API in the name. I will edit the proposal as such. @alefranz do you have any additions here? Thanks

**Comment by wordshaker** [comment]
> Hi @PeteDawson123
> 
> This seems rational - though I'd probably go further and suggest we shouldn't use "API" in those names at all as it's entirely implicit.
> 
> @alefranz @wordshaker thoughts?

I don't have any strong opinions on this point, to be honest. Likely only APIs will be documented as the "interaction" point for services, so I doubt we'll have many edge-cases where something isn't an API being documented. Likewise... it's 3 characters. Whichever you chose I don't think it'll be world-changing :)

**Review by alefranz — APPROVED** [review]
Seems reasonable and a good starting point to me!
Thanks @PeteDawson123 !

**Pull request merged**
