### PR TITLE
Update Documentation.md

### PR DESCRIPTION
**Pull request by justintravis**
# Description of the Change

Update documentation to remove instruction to tag individual devportal team members, as they will now be automatically tagged upon PR creation.

## Value

Accurately reflects the new tech lead on the DevPortal team!

## Applicable Issues

None

### CODE REVIEW

**Review by dturveyza — COMMENTED** [review]
maybe tagging a team would be better? then we don't need to update this as team members change?

**Comment by alefranz** [comment]
@justintravis if you are ok with the suggestion, let me know a name preference for the group and I can set one up in this org.

**Comment by justintravis** [comment]
@dturveyza @alefranz Great suggestion! How about we call it `DevPortal Content`? And add Megan and myself for now. And to be clear, I think it would need to be in the `NewDayCards` org rather than this one, since that's where the content repo is. Or does that not matter?

**Comment by wordshaker** [comment]
> @dturveyza @alefranz Great suggestion! How about we call it `DevPortal Content`? And add Megan and myself for now. And to be clear, I think it would need to be in the `NewDayCards` org rather than this one, since that's where the content repo is. Or does that not matter?

Does this still need doing? I can help set up a team in both orgs if it's of any help?

**Comment by justintravis** [comment]
@alefranz Awesome, thank you! I've added the CODEOWNERS file to the content repo and updated the instructions which are reflected in this PR.

**Comment by alefranz** [comment]
Brilliant! thanks!

**Review by alefranz — APPROVED** [review]

**Pull request merged**
